### ISSUE TITLE
Website stuck on loading

### ISSUE THREAD

**Issue by JanPokorny** [mertd/shovel#20]
When I visit https://shovel.sh/, the loading wheel spins indefinitely. The error console reads: `Uncaught (in promise) SyntaxError: Unexpected token in JSON at position 3107130 (asyncToGenerator.js:6)`

**Comment by mertd** [comment]
Thank you for opening an issue on this!

It seems the `nightlies` bucket currently contains a faulty manifest. Because of https://github.com/mertd/shovel-data/issues/8, the script gathering manifests for shovel doesn't have a way to identify and exclude broken buckets.

I temporarily removed the bucket in question from the indexing; the app should now work again! 
Also, I added an error message for similar cases in #21.

**Comment by mertd** [comment]
https://github.com/mertd/shovel-data/issues/8 is done and skips faulty manifests. This should prevent this crash from happening in the future.
